### ISSUE TITLE
Can I do it with just offsets?

### ISSUE THREAD

**Issue by ElatedEatrs** [achan1989/ghidra-65816#5]
I have the included offsets that come with Chrono compressor is that enough to decompile? I know this isn't an issue with the program, but there's no contact information for help.
Get in touch with me at this discord
https://discord.gg/RxT7Tvy

**Comment by achan1989** [comment]
I don't understand what you're asking, sorry.
This project lives in GitHub, I'm not going to use Discord to deal with issues.
