### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by lab313ru** [achan1989/ghidra-65816#6]
Hi,

are there any updates? Thank you for your efforts to create such a good thing for Ghidra.

**Comment by achan1989** [comment]
Thanks.  I haven't used this module in a while -- what updates do you think it needs?
Feel free to open some issues or submit a pull request ;)

**Comment by lab313ru** [comment]
Have you tried to analyze some SNES game using your module?

**Comment by achan1989** [comment]
Not really.  For SNES games, the module is of limited use by itself.

You need to set up the memory map correctly first, and while you can do this manually, it's extremely tedious.  Especially if you want the ROM mirroring and aliasing to be correct (although I don't know how important this is for a typical game).  It's also extremely helpful to have the memory-mapped IO in place (the PPU etc) -- this is also possible to do manually, but also tedious.

I started working on a [SNES loader](https://github.com/achan1989/ghidra-snes-loader) that would do this for you, but I never finished it.  I got distracted by other things.
